# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/network.crd.firemiles.top_networks.yaml
- bases/network.crd.firemiles.top_endpoints.yaml
- bases/network.crd.firemiles.top_subnets.yaml
- bases/network.crd.firemiles.top_ipblocks.yaml
- bases/network.crd.firemiles.top_workloads.yaml
- bases/network.crd.firemiles.top_endpointpools.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_networks.yaml
#- patches/webhook_in_endpoints.yaml
#- patches/webhook_in_subnets.yaml
#- patches/webhook_in_ipblocks.yaml
#- patches/webhook_in_workloads.yaml
#- patches/webhook_in_endpointpools.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_networks.yaml
#- patches/cainjection_in_endpoints.yaml
#- patches/cainjection_in_subnets.yaml
#- patches/cainjection_in_ipblocks.yaml
#- patches/cainjection_in_workloads.yaml
#- patches/cainjection_in_endpointpools.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
