# permissions to do edit endpointclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endpointclaim-editor-role
rules:
- apiGroups:
  - network.crd.firemiles.top
  resources:
  - endpointclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.crd.firemiles.top
  resources:
  - endpointclaims/status
  verbs:
  - get
  - patch
  - update
