# permissions to do edit endpointpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endpointpool-editor-role
rules:
- apiGroups:
  - network.crd.firemiles.top
  resources:
  - endpointpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.crd.firemiles.top
  resources:
  - endpointpools/status
  verbs:
  - get
  - patch
  - update
