# permissions to do viewer ipblocks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipblock-viewer-role
rules:
- apiGroups:
  - network.crd.firemiles.top
  resources:
  - ipblocks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.crd.firemiles.top
  resources:
  - ipblocks/status
  verbs:
  - get
