# permissions to do viewer subnets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subnet-viewer-role
rules:
- apiGroups:
  - network.crd.firemiles.top
  resources:
  - subnets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.crd.firemiles.top
  resources:
  - subnets/status
  verbs:
  - get
