# permissions to do viewer workloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workload-viewer-role
rules:
- apiGroups:
  - network.crd.firemiles.top
  resources:
  - workloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.crd.firemiles.top
  resources:
  - workloads/status
  verbs:
  - get
